# Generated by Django 6.0.3 on 2026-03-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='default_bank_iban',
            field=models.CharField(blank=True, default='', max_length=34),
        ),
        migrations.AddField(
            model_name='contact',
            name='default_bank_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='default_payment_method',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='contact',
            name='default_payment_terms',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
