# Generated by Django 6.0.3 on 2026-03-24 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('sales', 'Vendita'), ('purchase', 'Acquisto'), ('self_invoice', 'Autofattura')], max_length=20)),
                ('pattern', models.CharField(default='{SEQ}', max_length=100)),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VatRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('nature', models.CharField(blank=True, default='', max_length=10)),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-percent', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sales', 'Vendita'), ('purchase', 'Acquisto'), ('self_invoice', 'Autofattura')], default='sales', max_length=20)),
                ('number', models.CharField(max_length=50)),
                ('sequential_number', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('document_type', models.CharField(blank=True, default='', max_length=10)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('total_net', models.IntegerField(default=0)),
                ('total_vat', models.IntegerField(default=0)),
                ('total_gross', models.IntegerField(default=0)),
                ('withholding_tax_enabled', models.BooleanField(default=False)),
                ('withholding_tax_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('withholding_tax_amount', models.IntegerField(default=0)),
                ('payment_method', models.CharField(blank=True, default='', max_length=10)),
                ('payment_terms', models.CharField(blank=True, default='', max_length=10)),
                ('bank_name', models.CharField(blank=True, default='', max_length=100)),
                ('bank_iban', models.CharField(blank=True, default='', max_length=34)),
                ('vat_payability', models.CharField(default='I', max_length=1)),
                ('split_payment', models.BooleanField(default=False)),
                ('stamp_duty_applied', models.BooleanField(default=False)),
                ('stamp_duty_amount', models.IntegerField(default=0)),
                ('sdi_status', models.CharField(blank=True, default='', max_length=30)),
                ('sdi_uuid', models.CharField(blank=True, default='', max_length=100)),
                ('sdi_id', models.CharField(blank=True, default='', max_length=100)),
                ('sdi_message', models.TextField(blank=True, default='')),
                ('sdi_sent_at', models.DateTimeField(blank=True, null=True)),
                ('xml_content_hash', models.CharField(blank=True, db_index=True, default='', help_text='SHA-256 of imported XML to prevent duplicate imports', max_length=64)),
                ('last_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_delivery_status', models.CharField(blank=True, choices=[('', 'Non inviata'), ('sent', 'Inviata'), ('failed', 'Fallita')], default='', max_length=10)),
                ('related_invoice_number', models.CharField(blank=True, default='', max_length=50)),
                ('related_invoice_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contacts.contact')),
                ('related_invoice', models.ForeignKey(blank=True, help_text='Original invoice (for credit notes TD04)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes', to='invoices.invoice')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('invoices.invoice',),
        ),
        migrations.CreateModel(
            name='SelfInvoice',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('invoices.invoice',),
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_of_measure', models.CharField(blank=True, default='', max_length=10)),
                ('unit_price', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoices.invoice')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
