# Generated by Django 6.0.3 on 2026-03-24 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoices.sequence'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='vat_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoices.vatrate'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['type', 'date'], name='invoices_in_type_4f04df_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['contact_id'], name='invoices_in_contact_4168e3_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['sequence_id', 'date'], name='invoices_in_sequenc_c2cc95_idx'),
        ),
    ]
