# Generated by Django 6.0.3 on 2026-03-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_invoice_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='paid_at',
            field=models.DateField(blank=True, help_text='Data incasso effettivo', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid_via',
            field=models.CharField(blank=True, default='', help_text='Metodo di incasso effettivo (codice MP)', max_length=10),
        ),
    ]
