# Generated by Django 6.0.3 on 2026-03-24 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_add_paid_at_paid_via'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('amount', models.IntegerField(default=0, help_text='Importo in centesimi')),
                ('payment_method', models.CharField(blank=True, default='', max_length=10)),
                ('paid', models.BooleanField(db_index=True, default=False)),
                ('paid_at', models.DateField(blank=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_dues', to='invoices.invoice')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
