# Generated by Django 6.0.3 on 2026-04-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_add_payment_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='sealed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Bozza'), ('sealed', 'Sigillata'), ('outbox', 'In uscita'), ('sent', 'Inviata')], default='draft', max_length=20),
        ),
    ]
