# Generated by Django 6.0.3 on 2026-03-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorePermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('manage_settings', 'Può modificare impostazioni azienda'), ('manage_users', 'Può gestire utenti e gruppi')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
