# Generated by Django 6.0.3 on 2026-03-24 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_core_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corepermissions',
            options={'default_permissions': (), 'managed': False, 'permissions': [('manage_settings', 'Può modificare impostazioni azienda'), ('manage_users', 'Può gestire utenti e gruppi'), ('manage_fiscal_year', 'Può cambiare anno fiscale')]},
        ),
    ]
