# Generated by Django 6.0.3 on 2026-04-04 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0005_add_payment_due'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SdiLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('send_queued', 'Invio accodato'), ('send_success', 'Invio riuscito'), ('send_failed', 'Invio fallito'), ('status_changed', 'Stato aggiornato'), ('webhook_received', 'Webhook ricevuto'), ('webhook_rejected', 'Webhook rifiutato')], max_length=30)),
                ('sdi_uuid', models.CharField(blank=True, default='', max_length=100)),
                ('old_status', models.CharField(blank=True, default='', max_length=30)),
                ('new_status', models.CharField(blank=True, default='', max_length=30)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sdi_logs', to='invoices.invoice')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SDI Log',
                'verbose_name_plural': 'SDI Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['invoice', '-created_at'], name='sdi_sdilog_invoice_ddbfb2_idx'), models.Index(fields=['event', '-created_at'], name='sdi_sdilog_event_7e73a1_idx')],
            },
        ),
    ]
