# Generated by Django 6.0.3 on 2026-04-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdi', '0002_pa_skipped_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdilog',
            name='event',
            field=models.CharField(choices=[('send_queued', 'Invio accodato'), ('send_success', 'Invio riuscito'), ('send_failed', 'Invio fallito'), ('manual_send', 'Invio manuale (AdE/PEC)'), ('pa_skipped', 'PA: firma richiesta'), ('status_changed', 'Stato aggiornato'), ('webhook_received', 'Webhook ricevuto'), ('webhook_rejected', 'Webhook rifiutato')], max_length=30),
        ),
    ]
